---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Bitbucket Mirror
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
jobs:
  mirror:
    uses: aps831/workflows/.github/workflows/bitbucket-mirror.yaml@master
    with:
      username: UPDATE_ME
      repositoryname: UPDATE_ME
    secrets:
      BITBUCKET_SSH_PRIVATE_KEY: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
