---
name: Build and Publish Repository
on:
  push:
    branches:
      - "master"
      - "prerelease"
permissions:
  contents: write
  issues: write
  pull-requests: write
env:
  TFVARS_FILENAME: "terraform.tfvars"
  TFVARS_TAG: "image_tag"
  TFVARS_SEMVER_REGEX: "[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+"
jobs:
  build:
    uses: aps831/workflows/.github/workflows/build-and-publish-terraform.yaml@feat/deploy
    with:
      terraform-version: "1.4.2"
      paths: |
        moduleA
        moduleB
      # tfvars-filename: "terraform.tfvars"
      # tfvars-update-values: "tag|v[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+|v2.7.9"
      tfvars-filename: ${{ env.TFVARS_FILENAME }}
      tfvars-update-values:
        "${{ env.TFVARS_TAG }}|${{ env.TAG_PREFIX }}${{ env.TFVARS_SEMVER_REGEX }}|${{
        steps.control.outputs.tag-version-next }}"
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
