---
name: Build and Publish Repository
on:
  push:
  issue_comment:
    types:
      - created
  # push:
  #   branches:
  #     - "master"
  #     - "prerelease"
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  build:
    uses: aps831/workflows/.github/workflows/build-and-publish-terraform.yaml@master
    if:
      ${{ (github.event_name == 'push' && !contains(github.triggering_actor, '[bot]' )) ||
      (github.event.issue.pull_request && !contains(github.event.comment.body, '.noop') &&
      !contains(github.event.comment.body, '.deploy')) }}
    with:
      terraform-version: "1.4.2"
      paths: |
        dev
        prod
      release-on-default-branch: false
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
