name: Build and Publish Repository
on:
  # push:
  #   branches:
  #     - "master"
  #     - "prerelease"
  pull_request: {}
  issue_comment:
    types:
      - created
jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
    uses: aps831/workflows/.github/workflows/publish-terraform.yaml@refactor/build-release
    with:
      branch-prerelease: "prerelease"
      branch-update-base: "chore/publish-update"
      release-on-default-branch: false
      tag-prefix: "v"
      working-directory: "."
      terraform-version: "1.4.2"
      paths: |
        moduleA
        moduleB
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
