---
name: Build and Publish Repository
on:
  push:
    branches:
      - "master"
      - "prerelease"
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  build:
    uses: aps831/workflows/.github/workflows/build-and-publish-terraform.yaml@feat/deploy
    with:
      terraform-version: "1.4.2"
      paths: |
        moduleA
        moduleB
      # tfvars-filename: "terraform.tfvars"
      # tfvars-update-values: "tag|v[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+|v2.7.9"
      tfvars-filename: "terraform.tfvars"
      tfvars-update-values:
        "image_tag|v[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+|${{
        steps.control.outputs.tag-version-next }}"
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
