---
name: Build and Publish Repository
on:
  push:
    branches:
      - "master"
      - "prerelease"
jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: aps831/workflows/.github/workflows/build-and-publish-terraform.yaml@master
    with:
      terraform-version: "1.4.2"
      paths: |
        moduleA
        moduleB
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
