---
name: Deployment Candidate Sub
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  candidate:
    uses: aps831/workflows/.github/workflows/deployment-candidate-sub.yaml@feat/deploy
    with:
      tag: ${{ inputs.tag }}
      tfvars-filename: "terraform.tfvars"
      tfvars-update-values: "tag|v[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+|${{ inputs.tag }}"
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
